### ISSUE TITLE
Please provide more detailed example

### ISSUE THREAD

**Issue by johntdyer** [mf-social/ps-date-countdown#1]
It’s not clear to me exactly how I define the birthdays...  I see from the readme which fields you expect but what’s not clear to me is where I define these... Do they go in the configuration.yaml ?

**Comment by houtknots** [comment]
Same problem here, I do not understand how add this compent in the configuration file

**Comment by point-4ward** [comment]
This isn't a component, it's a python script - to see how to use it in homeassistant please scroll down the README file to the section 'Example configuration.yaml entry' - it's pretty self-explanatory.

The automation in that example runs the python script once a day, which creates/updates the countdown sensors.

**Comment by stefancvetkovic** [comment]
If I understood this correctly, for each reminder, I will have separate yaml file inside python_scripts folder?

**Comment by point-4ward** [comment]
No, you just use an automation to run the script as many times as you need to create the number of sensors you need. Please see the example in the Readme

**Comment by stefancvetkovic** [comment]
@mf-social 
Thanks, I saw, everything is clear, except for the lovelace representation?
In your example you provided sensor.anniversary_our_wedding but where did you registered this sensor? and this sensor is which type?
```type: entities
show_header_toggle: false
title: Our Events
entities:
  - entity: sensor.anniversary_our_wedding
    secondary_info: '[[ {entity}.attributes.nextoccur ]]  ( [[ {entity}.attributes.years ]] Years )'
    type: 'custom:secondaryinfo-entity-row'```

**Comment by point-4ward** [comment]
Define 'type' of sensor?

The sensor is 'registered' in the automation that runs the script.
```yaml
      - service: python_script.date_countdown
        data:
          name: Our wedding
          type: anniversary
          date: 14/02/1994
```

**Comment by stefancvetkovic** [comment]
I assumed, that this automation "register" sensors by its name right?
I tried to invoke automation with service call `automation.turn_on` but nothing happens, I cant see the sensors.
I also restarted HA, but sill nothing.
Even I changed trigger for my automation, to trigger on switch state `on`
So, definitely, I have a problem with recognising those sensors..

**Comment by stefancvetkovic** [comment]
Here is my automation example:
```- alias: Reminder - Refresh date countdown sensors
  trigger:
    - platform: state
      entity_id: switch.living_room_main_light
      from:  'off'
      to:  'on'
    # - platform: time
    #   at: '00:00:01'
    # - platform: homeassistant
    #   event: start
  action:
    - service: python_script.date_countdown
      data:
        name: Stefan's Birthday
        type: birthday
        date: 03/09/1989
    - service: python_script.date_countdown
      data:
        name: Ivan comming
        type: event
        date: 28/02/2020
```

**Comment by point-4ward** [comment]
Do you have

`python_script:`

Somewhere in your configuration.yaml?

**Comment by stefancvetkovic** [comment]
Yes, I have

**Comment by point-4ward** [comment]
When you trigger the automation, any errors in the log?

**Comment by point-4ward** [comment]
@stefancvetkovic - is this still a problem or have you sorted it?
