### ISSUE TITLE
Error python 3.9.0

### ISSUE THREAD

**Issue by MARIOP69** [mf-social/ps-date-countdown#18]
HA 0.116.4  with python 3.9.0 
Reminder - Refresh date countdown sensors: Error executing script. Unexpected error for call_service at pos 1: Unknown slice type: <ast.Constant object at 0x51578490>
While executing automation automation.reminder_refresh_date_countdown_sensors

**Comment by point-4ward** [comment]
Paste your automation please?

**Comment by MARIOP69** [comment]
##############################################################################
#                _                        _   _
#     /\        | |                      | | (_)
#    /  \  _   _| |_ ___  _ __ ___   __ _| |_ _  ___  _ __  ___
#   / /\ \| | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
#  / ____ \ |_| | || (_) | | | | | | (_| | |_| | (_) | | | \__ \
# /_/    \_\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/
#
###############################################################################
automation:
  - alias: Reminder - Refresh date countdown sensors
    trigger:
      - platform: time
        at: '00:00:01'
      - platform: homeassistant
        event: start
    action:
      - service: python_script.date_countdown
        data:
          name: Mario
          type: birthday
          date: 11/07/1969
      - service: python_script.date_countdown
        data:
          name: Patrizia
          type: birthday
          date: 08/10/1974
      - service: python_script.date_countdown
        data:
          name: Alessandro
          type: birthday
          date: 11/07/1999
      - service: python_script.date_countdown
        data:
          name: Laura
          type: birthday
          date: 24/10/2002
      - service: python_script.date_countdown
        data:
          name: Silvia
          type: birthday
          date: 15/02/2004
      - service: python_script.date_countdown
        data:
          name: Matrimonio
          type: anniversary
          date: 02/08/1998
          icon: "mdi:ring"
          append_year: True
      - service: python_script.date_countdown
        data:
          name: Fidanzamento
          type: celebration
          date: 19/08/1991
          #reverse: True

**Comment by point-4ward** [comment]
OK, that looks fine. I take it you had this working on an earlier python version? 

I can't reproduce the error here, and currently 3.9.0 isn't supposed to be used with homeassistant, 3.8.6 is the max currently supported with 0.116.x so I don't know whether this will just fix itself with 0.117 (or later) or whether I will need to adjust something in the script :man_shrugging:

I'll leave this open and see if I can reproduce it when homeassistant upgrades their bundled python version, and take it from there.

**Comment by MARIOP69** [comment]
Thank you. I wanted to upgrade to python 3.9.0 and currently having fixed a problem with ONVIF it is the only noticeable problem left

**Comment by point-4ward** [comment]
Yeah, I mean the error message implies that it's failing at the point where I split the date in to the individual day, month and year - but a quick Google doesn't seem to suggest that the syntax has changed, so hopefully this is just a compatability problem in homeassistant between the python_script component and the python version you're running that will be fixed when they move to officially support 3.9.

As I say, I'll keep an eye out for it and if I do need to adjust the script I will endeavour to find out how and do so promptly 👍

**Comment by point-4ward** [comment]
@MARIOP69

The latest release of homeassistant as of 5 days ago is based on 3.9 and I am still unable to recreate this error.

Is this still an issue for you, or can it be closed?
