### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by PierreScerri** [mf-social/ps-date-countdown#3]
Hi

I've installed the script as per instructions.
Not sure where I would put the birthday definitions.

Could I have a full example please?

Thank you.

**Comment by point-4ward** [comment]
Example in the Readme - just needs 'John's birthday' and 'our wedding anniversary' replacing with your first two sensors and any others tacking on the bottom in the same format.

**Comment by PierreScerri** [comment]
Got it now.  It is all in the automation.  Didn't get that at first.

Thank you.

**Comment by point-4ward** [comment]
No worries :+1:
