### ISSUE TITLE
Didnt work with my son's birthday

### ISSUE THREAD

**Issue by everything-tech-related** [mf-social/ps-date-countdown#6]
I use the date 13/03/2018 and its saying -650 days and the nextoccur shows his DOB not his next birthday.

**Comment by point-4ward** [comment]
Indeed, looks like if you use 2018 or 2019 for the year it goes screwy, 2017 and back works fine.

I'll have a look and try and work out why when I get chance :slightly_smiling_face:

**Comment by everything-tech-related** [comment]
Started working after HA Update
